
//  /sign-in 경로 이하의 모든 페이지에 적용되는 서브 레이아웃 컴포넌트
//  SignInpage 컴포넌트의 서브 레이아웃(sub-layout) 역할
/**
 * 사용자가 브라우저에서 http://localhost:3000/sign-in에 접속하면:
    Next.js는 app/sign-in/[[...sign-in]]/page.tsx의 SignInpage 컴포넌트를 찾음.
    그 페이지가 포함된 상위 디렉토리인 app/sign-in/에 layout.tsx가 있으므로,
    layout.tsx의 RootLayout이 먼저 실행되고,
    그 안의 {children} 자리에 SignInpage가 렌더링돼요.
 */
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* 여기에 SignInpage가 렌더링됨 */}
      <body>{children}</body>
    </html>
  )
}
